// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by AffineScript compiler (Deno-ESM target, issue #122)
// ---- AffineScript Deno-ESM runtime ----
const Some = (value) => ({ tag: "Some", value });
const None = { tag: "None" };
const Ok   = (value) => ({ tag: "Ok",  value });
const Err  = (error) => ({ tag: "Err", error });
const Unit = null;
const print   = (s) => { Deno.stdout.writeSync(new TextEncoder().encode(String(s))); };
const println = (s) => { console.log(String(s)); };
// ---- Deno host shims (extern fn lowering targets, issue #122) ----
// Kept tiny + inlined so emitted modules are genuinely drop-in (no extra
// package to publish or resolve). The same surface is mirrored, for
// standalone `deno test`, by packages/affine-deno/mod.js.
const __as_ensureDir = (p) => {
  try { Deno.mkdirSync(p, { recursive: true }); }
  catch (e) { if (!(e instanceof Deno.errors.AlreadyExists)) throw e; }
};
const __as_pathJoin = (a, b) => {
  if (a.length === 0) return b;
  const sep = a.endsWith("/") || a.endsWith("\\") ? "" : "/";
  return a + sep + b;
};
const __as_readDirNames = (p) => {
  const names = [];
  for (const entry of Deno.readDirSync(p)) {
    if (entry.isFile) names.push(entry.name);
  }
  return names;
};
const __as_isNotFound = (e) => (e instanceof Deno.errors.NotFound);
const __as_walkRecursive = (root) => {
  const out = [];
  const rec = (dir) => {
    for (const entry of Deno.readDirSync(dir)) {
      const full = (dir.endsWith("/") ? dir : dir + "/") + entry.name;
      if (entry.isFile) out.push(full);
      else if (entry.isDirectory) rec(full);
    }
  };
  rec(root);
  return out;
};
const __as_regexMatch = (s, pat) => new RegExp(pat).test(String(s));
const __as_wasmInstance = (bytes) =>
  new WebAssembly.Instance(new WebAssembly.Module(bytes)).exports;
const __as_wasmCall = (exports, name, args) => Number(exports[name](...(args || [])));
// ---- motion (bindings #4): consumer-provided import ----
// Host JS environment must expose globalThis.__as_motion (the motion
// library or a compatible mock). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import * as m from "motion"; globalThis.__as_motion = m;` once at
// module-init time. The AffineScript-side externs (stdlib/Motion.affine)
// don't see this indirection — they call __as_motion* helpers directly.
const __as_motionAnimate = (target, keyframes, options) =>
  globalThis.__as_motion.animate(target, keyframes, options);
const __as_motionAwait = (controls) =>
  Promise.resolve(controls).then(() => 0);
const __as_motionCancel = (controls) => {
  if (controls && typeof controls.cancel === "function") controls.cancel();
  return 0;
};
// `animateMini` / `tween` / `spring` / `ease` — bindings #4 follow-up
// surface. Each helper resolves the host method on globalThis.__as_motion
// at call time so a mock that only stubs a subset still works for the
// rest (the smoke harness exercises every variant).
const __as_motionAnimateMini = (target, keyframes, options) =>
  globalThis.__as_motion.animateMini(target, keyframes, options);
const __as_motionTween = (target, from, to, options) =>
  globalThis.__as_motion.tween(target, from, to, options);
const __as_motionSpring = (target, keyframes, springConfig) =>
  globalThis.__as_motion.spring(target, keyframes, springConfig);
const __as_motionEase = (name) =>
  globalThis.__as_motion.ease(name);
// ---- pixi.js (bindings #1): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi (the PIXI namespace
// from `import * as PIXI from "pixi.js"`). Tests set it in the harness
// before importing the generated module.
const __as_pixiAppInit = async (options) => {
  const app = new globalThis.__as_pixi.Application();
  await app.init(options);
  return app;
};
const __as_pixiAppCanvas = (app) => app.canvas;
const __as_pixiAppStage = (app) => app.stage;
const __as_pixiAppTicker = (app) => app.ticker;
const __as_pixiAppDestroy = (app) => { app.destroy(); return 0; };
const __as_pixiContainerNew = () => new globalThis.__as_pixi.Container();
const __as_pixiContainerAddChild = (p, c) => { p.addChild(c); return 0; };
const __as_pixiContainerRemoveChild = (p, c) => { p.removeChild(c); return 0; };
const __as_pixiContainerSetPosition = (c, x, y) => { c.x = x; c.y = y; return 0; };
const __as_pixiContainerSetVisible = (c, v) => { c.visible = v; return 0; };
const __as_pixiContainerDestroy = (c) => { c.destroy(); return 0; };
const __as_pixiSpriteFrom = (t) => new globalThis.__as_pixi.Sprite(t);
// Upcasts are identity — PIXI's class hierarchy makes Sprite/Graphics/
// Text actual Container subclasses, so the JS object is the same.
const __as_pixiSpriteAsContainer = (s) => s;
const __as_pixiTextureFromUrl = (url) => globalThis.__as_pixi.Texture.from(url);
const __as_pixiGraphicsNew = () => new globalThis.__as_pixi.Graphics();
const __as_pixiGraphicsRect = (g, x, y, w, h) => { g.rect(x, y, w, h); return 0; };
const __as_pixiGraphicsFill = (g, color) => { g.fill({ color }); return 0; };
const __as_pixiGraphicsClear = (g) => { g.clear(); return 0; };
const __as_pixiGraphicsAsContainer = (g) => g;
const __as_pixiTextNew = (options) => new globalThis.__as_pixi.Text(options);
const __as_pixiTextSetText = (t, content) => { t.text = content; return 0; };
const __as_pixiTextAsContainer = (t) => t;
const __as_pixiTickerAdd = (t, cb) => { t.add(cb); return 0; };
const __as_pixiTickerStart = (t) => { t.start(); return 0; };
const __as_pixiTickerStop = (t) => { t.stop(); return 0; };
// ---- @pixi/ui (bindings #3): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_ui (the namespace
// from `import * as PixiUI from "@pixi/ui"`). Tests set it in the
// harness before importing the generated module; production
// consumers typically do once at module-init time. The
// AffineScript-side externs (stdlib/PixiUI.affine) don't see this
// indirection — they call __as_pixiUi* helpers directly.
//
// Upcasts to Container are identity — @pixi/ui's Button /
// FancyButton / Slider / Switch are all real PIXI.Container
// subclasses, so the JS object is the same.
const __as_pixiUiButtonNew         = (options) => new globalThis.__as_pixi_ui.Button(options);
const __as_pixiUiButtonOnPress     = (b, cb)   => { b.onPress.connect(cb); return 0; };
const __as_pixiUiButtonAsContainer = (b)       => b;
const __as_pixiUiFancyButtonNew         = (options) => new globalThis.__as_pixi_ui.FancyButton(options);
const __as_pixiUiFancyButtonAsContainer = (b)       => b;
const __as_pixiUiSliderNew         = (options) => new globalThis.__as_pixi_ui.Slider(options);
const __as_pixiUiSliderOnUpdate    = (s, cb)   => { s.onUpdate.connect(cb); return 0; };
const __as_pixiUiSliderAsContainer = (s)       => s;
const __as_pixiUiSwitchNew         = (options) => new globalThis.__as_pixi_ui.Switch(options);
const __as_pixiUiSwitchOnChange    = (sw, cb)  => { sw.onChange.connect(cb); return 0; };
const __as_pixiUiSwitchAsContainer = (sw)      => sw;
// ---- @pixi/sound (bindings #2): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_sound (the `Sound`
// named export from `@pixi/sound`). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import { Sound } from "@pixi/sound"; globalThis.__as_pixi_sound = Sound;`
// once at module-init time. The AffineScript-side externs
// (stdlib/PixiSound.affine) don't see this indirection — they call
// __as_pixiSound* helpers directly.
const __as_pixiSoundFrom = (url) => globalThis.__as_pixi_sound.from(url);
const __as_pixiSoundPlay = (s) => { s.play(); return 0; };
const __as_pixiSoundStop = (s) => { s.stop(); return 0; };
const __as_pixiSoundPause = (s) => { s.pause(); return 0; };
const __as_pixiSoundResume = (s) => { s.resume(); return 0; };
const __as_pixiSoundSetVolume = (s, vol) => { s.volume = vol; return 0; };
const __as_pixiSoundSetLoop = (s, loop) => { s.loop = loop; return 0; };
// `++` is overloaded (string concat / array concat); `a + b` would
// stringify arrays. Dispatch on shape so stdlib/string.affine's
// `result ++ [x]` and `a ++ b` are both correct.
const __as_concat = (a, b) => Array.isArray(a) ? a.concat(b) : (a + b);
// Honest host/runtime primitives underpinning the AffineScript-level
// stdlib/string.affine (its is_empty/starts_with/ends_with/split/join/
// replace/... are real AffineScript on top of these).
const __as_strSub = (s, start, n) => String(s).slice(start, start + n);
const __as_strGet = (s, i) => String(s)[i];
const __as_strFind = (s, n) => String(s).indexOf(n);
const __as_charToInt = (c) => String(c).codePointAt(0);
const __as_intToChar = (n) => String.fromCodePoint(n);
const __as_parseInt = (s) => {
  const n = parseInt(String(s), 10);
  return Number.isNaN(n) ? None : Some(n);
};
const __as_parseFloat = (s) => {
  const n = parseFloat(String(s));
  return Number.isNaN(n) ? None : Some(n);
};
const __as_show = (v) => (typeof v === "string" ? v : JSON.stringify(v));
// ---- Http (issue #160): portable fetch round-trip ----
// `headers` crosses the boundary as an AffineScript [(String, String)]
// assoc list == JS array of [name, value] pairs. `body` is an
// AffineScript Option<String> == { tag: "Some", value } | { tag: "None" }.
// The result is the `Response` record shape { status, headers, body }.
const __as_httpHeadersToObject = (pairs) => {
  const o = {};
  for (const kv of (pairs || [])) o[kv[0]] = kv[1];
  return o;
};
const __as_httpHeadersFromResponse = (res) => {
  const out = [];
  res.headers.forEach((value, key) => out.push([key, value]));
  return out;
};
// ---- hpm-json-rsr Zig FFI shims (stdlib/json.affine v0.3) ----
// `HpmJsonValue` is opaque to AffineScript; on Deno-ESM it's just the
// underlying JS value from JSON.parse. The shims mirror the sentinel
// conventions of the Zig exports so the AffineScript-side wrappers
// (`to_json`, `parse`) behave identically across backends.
const __as_hpmJsonParse = (s) => {
  try { return Some(JSON.parse(String(s))); } catch (_e) { return None; }
};
const __as_hpmJsonFree = (_v) => 0;
const __as_hpmJsonType = (v) => {
  if (v === null || v === undefined) return 0;
  if (typeof v === "boolean") return 1;
  if (typeof v === "number")  return Number.isInteger(v) ? 2 : 3;
  if (typeof v === "string")  return 4;
  if (Array.isArray(v))       return 5;
  if (typeof v === "object")  return 6;
  return -1;
};
const __as_hpmJsonBool = (v) => (typeof v === "boolean" ? (v ? 1 : 0) : -1);
const __as_hpmJsonInt = (v) =>
  (typeof v === "number" ? Math.trunc(v) : Number.MIN_SAFE_INTEGER);
const __as_hpmJsonFloat = (v) => (typeof v === "number" ? v : NaN);
const __as_hpmJsonString = (v) => (typeof v === "string" ? v : "");
const __as_hpmJsonObjectGet = (v, k) => {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return None;
  return Object.prototype.hasOwnProperty.call(v, String(k))
    ? Some(v[String(k)]) : None;
};
const __as_hpmJsonArrayLen = (v) => (Array.isArray(v) ? v.length : 0);
const __as_hpmJsonArrayGet = (v, i) => {
  if (!Array.isArray(v)) return None;
  const idx = Number(i);
  return (idx >= 0 && idx < v.length) ? Some(v[idx]) : None;
};
const __as_hpmJsonEscapeString = (s) => {
  let out = "";
  const src = String(s);
  for (let i = 0; i < src.length; i++) {
    const c = src.charCodeAt(i);
    if (c === 0x22) out += "\\\"";
    else if (c === 0x5c) out += "\\\\";
    else if (c === 0x0a) out += "\\n";
    else if (c === 0x0d) out += "\\r";
    else if (c === 0x09) out += "\\t";
    else if (c === 0x08) out += "\\b";
    else if (c === 0x0c) out += "\\f";
    else if (c < 0x20) out += "\\u00" + c.toString(16).padStart(2, "0");
    else out += src[i];
  }
  return out;
};
const __as_httpFetch = async (url, method, headers, bodyOpt) => {
  const init = { method, headers: __as_httpHeadersToObject(headers) };
  if (bodyOpt && bodyOpt.tag === "Some") init.body = bodyOpt.value;
  // `globalThis.fetch` explicitly: the stdlib `Http.fetch` compiles to a
  // module-level `function fetch`, which would otherwise shadow the host.
  const res = await globalThis.fetch(url, init);
  const text = await res.text();
  return {
    status: res.status,
    headers: __as_httpHeadersFromResponse(res),
    body: text,
  };
};
// ---- end runtime ----

export function split(s, delimiter) {
  const slen = ((s).length);
  const dlen = ((delimiter).length);
  if ((dlen === 0)) { let result = []; let i = 0; while ((i < slen)) { result = __as_concat(result, [__as_strSub(s, i, 1)]); i = (i + 1); } return result;  }
  let result = [];
  let current_start = 0;
  let i = 0;
  while ((i <= (slen - dlen))) {  if ((__as_strSub(s, i, dlen) === delimiter)) { result = __as_concat(result, [__as_strSub(s, current_start, (i - current_start))]); current_start = (i + dlen); i = (i + dlen);  } else { i = (i + 1);  } }
  result = __as_concat(result, [__as_strSub(s, current_start, (slen - current_start))]);
  return result;
}

const REPO_ROOT = ".";
const PDF_NAME = "Tropical Resource Typing For Protocols.pdf";
function ends_with(s, suffix) {
  const slen = ((s).length);
  const sfxlen = ((suffix).length);
  return ((sfxlen > slen) ? (() => { return false; })() : (() => { return (__as_strSub(s, (slen - sfxlen), sfxlen) === suffix); })());
}

function contains_str(haystack, needle) {
  return (__as_strFind(haystack, needle) >= 0);
}

function assert_true(condition, message) {
  if ((!condition)) { const _id0 = (console.error(__as_concat("FAIL: ", message)), 0); return Deno.exit(1);  }
  return 0;
}

function file_size_or_neg(path) {
  const sz = (() => { try { return (() => { return Deno.statSync(path).size; })(); } catch (__e) { return (0 - 1); } })();
  return sz;
}

function file_exists(path) {
  return (file_size_or_neg(path) >= 0);
}

function read_text_or_empty(path) {
  const s = (() => { try { return (() => { return Deno.readTextFileSync(path); })(); } catch (__e) { return ""; } })();
  return s;
}

function is_binary_name(name) {
  const lname = String(name).toLowerCase();
  if (ends_with(lname, ".pdf")) { return true;  }
  if (ends_with(lname, ".png")) { return true;  }
  if (ends_with(lname, ".jpg")) { return true;  }
  if (ends_with(lname, ".jpeg")) { return true;  }
  if (ends_with(lname, ".gif")) { return true;  }
  if (ends_with(lname, ".ico")) { return true;  }
  if (ends_with(lname, ".woff")) { return true;  }
  if (ends_with(lname, ".woff2")) { return true;  }
  return false;
}

function under_git_dir(path) {
  const segs = split(path, "/");
  let i = 0;
  const n = ((segs).length);
  while ((i < n)) { const seg = segs[i]; if (((((seg).length) >= 4) && (__as_strSub(seg, 0, 4) === ".git"))) { return true;  } i = (i + 1); }
  return false;
}

function collect_text_files(root) {
  const all = (() => { try { return (() => { return __as_walkRecursive(root); })(); } catch (__e) { return []; } })();
  let out = [];
  let i = 0;
  const n = ((all).length);
  while ((i < n)) { const f = all[i]; if (((!under_git_dir(f)) && (!is_binary_name(f)))) { out = __as_concat(out, [f]);  } i = (i + 1); }
  return out;
}

function unit_pdf_exists() {
  const path = __as_pathJoin(REPO_ROOT, PDF_NAME);
  return assert_true(file_exists(path), __as_concat("unit: PDF artefact must exist: ", PDF_NAME));
}

function unit_readme_exists() {
  return assert_true(file_exists(__as_pathJoin(REPO_ROOT, "README.md")), "unit: README.md must be a regular file");
}

function unit_license_exists() {
  return assert_true(file_exists(__as_pathJoin(REPO_ROOT, "LICENSE")), "unit: LICENSE must be a regular file");
}

function smoke_pdf_nonzero() {
  const sz = file_size_or_neg(__as_pathJoin(REPO_ROOT, PDF_NAME));
  return assert_true((sz > 0), "smoke: PDF must have non-zero file size");
}

function smoke_pdf_above_1kb() {
  const sz = file_size_or_neg(__as_pathJoin(REPO_ROOT, PDF_NAME));
  return assert_true((sz > 1024), "smoke: PDF must be larger than 1KB -- smaller files are likely stubs");
}

function smoke_readme_nonempty() {
  const content = read_text_or_empty(__as_pathJoin(REPO_ROOT, "README.md"));
  return assert_true((((String(content).trim()).length) > 0), "smoke: README.md must not be empty");
}

function smoke_license_nonempty() {
  const content = read_text_or_empty(__as_pathJoin(REPO_ROOT, "LICENSE"));
  return assert_true((((String(content).trim()).length) > 0), "smoke: LICENSE must not be empty");
}

function p2p_all_text_utf8() {
  const text_files = collect_text_files(REPO_ROOT);
  let errors = [];
  let i = 0;
  const n = ((text_files).length);
  while ((i < n)) { const f = text_files[i]; const _id1 = (() => { try { return (() => { const _content = Deno.readTextFileSync(f); return 0; })(); } catch (__e) { return (() => { errors = __as_concat(errors, [f]); return 0; })(); } })(); i = (i + 1); }
  return assert_true((((errors).length) === 0), __as_concat(__as_concat("p2p: ", String(((errors).length))), " file(s) failed UTF-8 read"));
}

function p2p_pdf_is_binary() {
  const pdf_path = __as_pathJoin(REPO_ROOT, PDF_NAME);
  const _bytes = Deno.readFileSync(pdf_path);
  const sz = Deno.statSync(pdf_path).size;
  return assert_true((sz > 5), "p2p: PDF must be at least 5 bytes (the '%PDF-' header length)");
}

function e2e_readme_mentions_topic() {
  const readme_path = __as_pathJoin(REPO_ROOT, "README.md");
  const stage1 = file_exists(readme_path);
  const _id2 = assert_true(stage1, "e2e stage 1: README.md must exist");
  const content = read_text_or_empty(readme_path);
  const _id3 = assert_true((((content).length) > 0), "e2e stage 2: README.md must be readable and non-empty");
  const lower = String(content).toLowerCase();
  return assert_true((((contains_str(lower, "tropical") || contains_str(lower, "resource typing")) || contains_str(lower, "protocol")) || contains_str(lower, "mpl")), "e2e stage 3: README must reference the project topic (tropical, resource typing, protocol, or license)");
}

function e2e_pdf_chain() {
  const pdf_path = __as_pathJoin(REPO_ROOT, PDF_NAME);
  const _id4 = assert_true(file_exists(pdf_path), "e2e stage 1: PDF must exist");
  const sz = Deno.statSync(pdf_path).size;
  const _id5 = assert_true((sz > 0), "e2e stage 2: PDF size must be > 0");
  const _bytes = Deno.readFileSync(pdf_path);
  return assert_true((sz > 5), "e2e stage 3: PDF must be at least the magic-byte header length");
}

function e2e_license_chain() {
  const license_path = __as_pathJoin(REPO_ROOT, "LICENSE");
  const _id6 = assert_true(file_exists(license_path), "e2e: LICENSE must exist");
  const content = read_text_or_empty(license_path);
  return assert_true((((content).length) > 100), "e2e: LICENSE must have substantial content");
}

function contract_readme_has_heading() {
  const content = read_text_or_empty(__as_pathJoin(REPO_ROOT, "README.md"));
  const lines = split(content, "\n");
  let has_atx = false;
  let i = 0;
  const n = ((lines).length);
  while ((i < n)) { const line = lines[i]; if (((((line).length) > 0) && (__as_strSub(line, 0, 1) === "#"))) { has_atx = true;  } i = (i + 1); }
  const has_setext = (contains_str(content, "===") || contains_str(content, "---"));
  return assert_true((has_atx || has_setext), "contract: README.md must contain at least one heading (# ATX or setext)");
}

function contract_license_recognised() {
  const content = read_text_or_empty(__as_pathJoin(REPO_ROOT, "LICENSE"));
  const mentions = ((((((contains_str(content, "Mozilla Public License") || contains_str(content, "MPL")) || contains_str(content, "Palimpsest")) || contains_str(content, "PMPL")) || contains_str(content, "MIT License")) || contains_str(content, "Apache License")) || contains_str(content, "GNU General Public License"));
  return assert_true(mentions, "contract: LICENSE must reference a recognised license identifier");
}

function aspect_no_template_placeholders() {
  const content = read_text_or_empty(__as_pathJoin(REPO_ROOT, "README.md"));
  const _id7 = assert_true((!contains_str(content, "{{REPO}}")), "aspect: README.md contains unresolved placeholder: {{REPO}}");
  const _id8 = assert_true((!contains_str(content, "{{OWNER}}")), "aspect: README.md contains unresolved placeholder: {{OWNER}}");
  const _id9 = assert_true((!contains_str(content, "{{FORGE}}")), "aspect: README.md contains unresolved placeholder: {{FORGE}}");
  return assert_true((!contains_str(content, "YOUR_REPO_NAME")), "aspect: README.md contains unresolved placeholder: YOUR_REPO_NAME");
}

function aspect_pdf_filename_matches_topic() {
  const lname = String(PDF_NAME).toLowerCase();
  return assert_true(((contains_str(lname, "tropical") || contains_str(lname, "resource")) || contains_str(lname, "typing")), __as_concat(__as_concat("aspect: PDF filename '", PDF_NAME), "' should contain project-relevant terms"));
}

function benchmark_full_scan_completes() {
  const text_files = collect_text_files(REPO_ROOT);
  let i = 0;
  const n = ((text_files).length);
  while ((i < n)) { const f = text_files[i]; const _id10 = (() => { try { return (() => { return Deno.readTextFileSync(f); })(); } catch (__e) { return ""; } })(); i = (i + 1); }
  println(__as_concat(__as_concat("  benchmark: scanned ", String(n)), " text files"));
  return 0;
}

export function main() {
  println("Running tropical-resource-typing validation suite...");
  const _id11 = unit_pdf_exists();
  const _id12 = unit_readme_exists();
  const _id13 = unit_license_exists();
  const _id14 = smoke_pdf_nonzero();
  const _id15 = smoke_pdf_above_1kb();
  const _id16 = smoke_readme_nonempty();
  const _id17 = smoke_license_nonempty();
  const _id18 = p2p_all_text_utf8();
  const _id19 = p2p_pdf_is_binary();
  const _id20 = e2e_readme_mentions_topic();
  const _id21 = e2e_pdf_chain();
  const _id22 = e2e_license_chain();
  const _id23 = contract_readme_has_heading();
  const _id24 = contract_license_recognised();
  const _id25 = aspect_no_template_placeholders();
  const _id26 = aspect_pdf_filename_matches_topic();
  const _id27 = benchmark_full_scan_completes();
  println("OK: all checks passed");
  return 0;
}

await main();
